angular.module("mcc",[]);
angular.module("mcc").directive("mccAjaxScope",["$http",function(e){return{restrict:"A",scope:"@",link:function(c,a,d){void 0!=d.mccLoadingVar&&void 0==c[d.mccLoadingVar]&&(c[d.mccLoadingVar]=!0);"mccAjaxLog"in d&&console.log("Fetching data from "+d.mccAjaxScope);e({method:"GET",url:d.mccAjaxScope}).success(function(a,f,e,g){void 0!=d.mccLoadingVar&&(c[d.mccLoadingVar]=!c[d.mccLoadingVar],console.log(c));void 0==d.mccAjaxScopeVar&&(d.mccAjaxScopeVar="mcc_ajax");c[d.mccAjaxScopeVar]=a;"mccAjaxLog"in
d&&console.log(a)}).error(function(a,f,c,g){console.log("Error in ajax-scope. There's nothing I can do. (url: "+d.mccAjaxScope+")")})}}}]);angular.module("mcc").directive("mccAngularExpr",["$compile",function(e){return{restrict:"A",transclude:!0,scope:{value:"=mccAngularExpr"},link:function(c,a,d){c.$watch("value",function(){if(!(void 0==c.value||1>c.value.length)){var b=d.angularExprWrap;void 0==b&&(b="span");b=e("<"+b+">"+c.value+"</"+b+">")(c);$(a).empty();a.append(b)}})}}}]);
angular.module("mcc").directive("mccBackStretchCarousel",["$swipe",function(e){return{restrict:"A",compile:function(c,a){return function(a,b,f){f=b.parent()[0].clientHeight;$(b).css("height",f);a.$watch("images",function(f){if(0!==f.length){null!==$(b).children()&&$($(b).children()).remove();try{var c=$(".app-content")[0],n=$(c).height(),p=$(c).width();$(b).css("height",n).css("width",p)}catch(l){}$(b).backstretch(f,{duration:3E3,fade:700});var m=0;(function(){var f,c,g;e.bind(b,{start:function(a){f=
null;c=a.x},cancel:function(a){f=null;a.stopPropagation()},end:function(c,g){"prev"===f?m=0===m?a.images.length-1:m-1:"next"===f&&(m=m===a.images.length-1?0:m+1);null!==f&&$(b).backstretch("show",m);g.stopPropagation()},move:function(a){g=a.x-c;a=g/b[0].clientWidth;f=.2<a?"next":-.2>a?"prev":null}})})();var k=document.createElement("div");$(window).on("backstretch.before",function(a,b,f){a=$(k).children();$(a).removeClass("active");$(a[f]).addClass("active");m=f});$(k).addClass("mccBackStretchCarouselList").appendTo(b);
c=function(a,f){$(a).bind("click touch",function(){$(b).backstretch("show",f)})};for(n=0;n<f.length;n++)p=document.createElement("a"),0===n&&$(p).addClass("active"),$(p).appendTo(k),c(p,n)}})}}}}]);angular.module("mcc").directive("mccBindKeys",function(){return{restrict:"A",link:function(e,c,a){$(c).keydown(function(c){c.metaKey&&83===c.keyCode&&(e[a.bindKeysCtrlS](!1),c.preventDefault())})}}});
angular.module("mcc").directive("mccCanvasFollowMouse",["$http",function(e){return{restrict:"A",scope:{fun:"=mccCanvasFollowMouse"},link:function(c,a,d){a[0].addEventListener("mousemove",function(b){var f=a[0].getBoundingClientRect();c.fun(b.clientX-f.left,b.clientY-f.top)},!1)}}}]);
angular.module("mcc").directive("mccCodePage",["$rootScope","mcc.code",function(e,c){return{restrict:"A",replace:!1,templateUrl:function(a,c){return"rest/mcc/templates/codepages/"+c.mccCodePage},link:function(a,d,b){a.dataObject={};var f=b.mccCodePage;a.showCodeEditor=function(){c.get(f).then(function(b){a.dataObject=b.data.data;e.toggle("mcc.overlayEditorData","on")})}}}}]);
angular.module("mcc").directive("mccCodePageAdmin",["$rootScope","mcc.code",function(e,c){return{restrict:"E",templateUrl:"rest/mcc/templates/directives/codePageAdmin",link:function(a,d,b){a.dataObject={};a.showCodeEditor=function(b){c.get(b).then(function(b){a.dataObject=b.data.data;e.toggle("mcc.overlayEditorData","on")})}}}}]);
angular.module("mcc").directive("mccCodePageCreate",["$route","mcc.code","mcc.toasterTranslate",function(e,c,a){return{restrict:"A",scope:!1,link:function(d,b,f){d.create=function(){c.create({code:f.mccCodePageCreate,title:f.mccCodePageCreate}).then(function(b){a.success(b.dict)})}}}}]);
angular.module("mcc").directive("mccDatetime",[function(){return{restrict:"E",scope:{timestamp:"=timestamp"},templateUrl:"rest/mcc/templates/directives/datetime",link:function(e,c,a){e.opts={showWeeks:!0,hourStep:1,minuteStep:10,showMeridian:!1,startingDay:1,dateFormat:"dd.MM.yyyy",readonlyTime:!1};e.$watch("timestamp",function(){e.timeObject=new Date(e.timestamp)});e.$watch("timeObject",function(){e.timestamp=Math.floor(e.timeObject.getTime())})}}}]);
angular.module("mcc").directive("mccEditorData",["mcc.toasterTranslate","mcc.code",function(e,c){return{restrict:"A",transclude:!0,scope:{data:"=overlayData"},templateUrl:"rest/mcc/templates/directives/editorData",link:function(a,d,b){a.editorACE=!0;a.show="editor";a.figureCancel=function(){a.show="editor"};a.fileSaveCallback=function(b,c){ace.edit("aceEditor_content").insert(b.isImage?'<p>\n  <figure>\n    <img src="'+b.relPath+'">\n    <figcaption></figcaption>\n  </figure>\n</p>':'<a href="'+b.relPath+
'" target="blank"></a>');a.show="editor"};a.fileReceived=function(b){-1!==b.type.indexOf("image")?(a.$root.$broadcast("editFigure",{figure:b,params:{resize:800}}),a.show="figure",a.$apply()):console.log("Received other file than figure - action not implemented.")};a.save=function(){delete a.data.created;delete a.data.updated;c.update(a.data).then(function(a){e.report(a.status,a.data.dict)})}}}}]);
angular.module("mcc").directive("mccEditorFigure",["$http","mcc.toasterTranslate",function(e,c){return{restrict:"E",templateUrl:"rest/mcc/templates/directives/editorFigure",scope:{onSave:"=figureSave",onCancel:"=figureCancel"},link:function(a,d,b){a.show="loading";a.$on("editFigure",function(b,c){a.fe=new mcc.figureEditor({id:"mcc-editor-figure-canvas",maxWidth:750,maxHeight:500});a.figure=c.figure;a.params=c.params;a.fe.drawFullImage(a.figure,function(){a.show="loaded";a.$apply()});a.params.name=
a.figure.name});a.mousePosition=function(b,c){a.mouse={x:b,y:c};a.$apply()};a.recordMouseClick=function(){a.setCropPoint()};a.saveToServer=function(){a.show="uploading";var b=new FormData;b.append("file",a.figure);b.append("resize",a.params.resize);b.append("name",a.params.name);b.append("crop",JSON.stringify(a.fe.getCropPoints()));e.post("rest/private/files",b,{withCredentials:!0,headers:{"Content-Type":void 0},transformRequest:angular.identity}).success(function(b,f,d,e){c.common("success","FILE_UPLOADED");
a.show="uploaded";a.onSave(b,a.params)}).error(function(b,f,d,e){a.show="uploadedError";c.error(b.dict)})};a.setCropPoint=function(){a.fe.setCropPoint(a.mouse.x,a.mouse.y)}}}}]);
angular.module("mcc").directive("mccEditorNews",["$http","$rootScope","mcc.toasterTranslate","dialogs",function(e,c,a,d){return{restrict:"A",transclude:!0,scope:{news:"=mccEditorNews",cbDelete:"=deleteCb",cbAdd:"=saveCb"},templateUrl:"rest/mcc/templates/directives/editorNews",link:function(b,f,h){b.figure=null;var g=h.newsOverlay;b.editorACE=!0;b.modify=!("new"in h);b.show="editor";b.figureParam={ingres:{resize:400,type:"ingress"},contents:{resize:800,type:"contents"}};b.figureCancel=function(){b.show=
"editor"};b.del=function(f){d.confirm(void 0,void 0,{size:"sm"}).result.then(function(){e({method:"DELETE",url:"rest/private/news/"+f}).success(function(f,d,e,h){a.success(f.dict);c.toggle(g,"off");b.cbDelete()}).error(function(b,c,f,d){a.error(b.dict)})},function(){a.info("DELETE_CANCELLED")})};b.fileReceived=function(a,c,f){-1!==a.type.indexOf("image")?(b.$root.$broadcast("editFigure",{figure:a,params:f}),b.show="figure",b.$apply()):console.log("Received other file than figure - action not implemented.")};
b.setCurrentTime=function(){e({method:"GET",url:"rest/private/news/"+b.news.id+"/settocurrenttime"}).success(function(b,c,f,d){a.success(b.dict)}).error(function(b,c,f,d){a.error(b.dict)})};b.save=function(f){f=0<arguments.length?f:!0;b.modify?e({method:"PUT",data:b.news,url:"rest/private/news"}).success(function(b,d,e,h){a.success(b.dict);f&&c.toggle(g,"off")}).error(function(b,c,f,d){a.error(b.dict)}):(void 0==b.news.published&&(b.news.published=!1),e({method:"POST",data:{title:b.news.title,contents:b.news.contents,
ingress:b.news.ingress,published:b.news.published},url:"rest/private/news"}).success(function(f,d,e,h){a.success(f.dict);c.toggle(g,"off");b.cbAdd()}).error(function(b,c,f,d){a.error(b.dict)}))};b.fileSaveCallback=function(c,f){ace.edit("aceEditor_"+f.type).insert(c.isImage&&"contents"==b.figure.type?'<p>\n  <figure>\n    <img src="'+c.relPath+'">\n    <figcaption></figcaption>\n  </figure>\n</p>':c.isImage?'<img src="'+c.relPath+'">\n':'<a href="'+c.relPath+'" target="blank"></a>');b.$apply();a.common("success",
"FILE_UPLOADED");b.show="editor"}}}}]);
angular.module("mcc").directive("mccFileDropZone",function(){return{restrict:"A",scope:{onDrop:"=fileDropZoneOnDrop",onDragover:"=fileDropZoneOnDragover",onDragleave:"=fileDropZoneOnDragleave",param:"=fileDropZoneParam"},link:function(e,c,a){void 0==e.param&&(e.param={});c[0].addEventListener("dragover",function(a){a.preventDefault();if(void 0!=e.onDragover)e.onDragover(c[0],e.param)},!1);c[0].addEventListener("dragleave",function(a){a.preventDefault();if(void 0!=e.onDragleave)e.onDragleave(c[0],
e.param)},!1);c[0].addEventListener("drop",function(d){d.preventDefault();if("fileDropZoneMultiple"in a)e.onDrop(d.dataTransfer.files,c[0],e.param);else e.onDrop(d.dataTransfer.files[0],c[0],e.param)},!1)}}});
angular.module("mcc").directive("mccIsPast",["$http",function(e){return{restrict:"A",scope:!1,link:function(c,a,d){c[""==d.mccIsPast?"isPast":d.mccIsPast]=function(a,c,d){var g=new Date;a=new Date(d,c-1,a);return g.getTime()>a.getTime()+864E5?"past":g.getTime()>a.getTime()?"today":g.getTime()+864E5>a.getTime()?"tomorrow":g.getTime()+5184E5>a.getTime()?"next":""}}}}]);
angular.module("mcc").directive("mccLoginOverlay",["mcc.user","$rootScope","mcc.toasterTranslate",function(e,c,a){return{restrict:"E",scope:!0,templateUrl:"rest/mcc/templates/directives/loginOverlay",link:function(d,b,f){var h=function(){d.loginForm={username:"",password:""}};h();d.clickLogin=function(){d.loginInProgress=!0;e.login(d.loginform.username,d.loginform.password).success(function(b,f,d,l){c.toggle("mcc.loginOverlay","off");e.setLoginData(!0,b);a.success(b.dict);h()}).error(function(b,c,
f,e){d.loginFailed=!0;d.loginInProgress=!1;a.error(b.dict)})};d.clickLogout=function(){e.logout().success(function(b,f,d,h){e.setLoginData(!1);c.toggle("mcc.loginOverlay","off");a.success(b.dict)}).error(function(b,c,f,d){a.error(b.dict)})}}}}]);
angular.module("mcc").directive("mccModal",["$modal",function(e){return{restrict:"A",scope:{data:"=mccModalData"},link:function(c,a,d){a.bind("click",function(){var a;a=e.open({templateUrl:d.mccModal,size:d.mccModalSize,controller:d.mccModalController,resolve:{data:function(){return c.data},modalInstance:function(){return a}}})})}}}]);
angular.module("mcc").directive("mccNews",["$rootScope","mcc.newsData",function(e,c){return{restrict:"E",scope:!0,templateUrl:"rest/mcc/templates/directives/news",link:function(a,d,b){a.scrollCb=function(){};var f=function(){a.loadInProgress=!1;a.isInitialized=!1;a.news={data:[],pagination:{}}};f();var h=function(b){a.news.pagination=b.pagination;a.news.data=a.news.data.concat(b.news);a.loadInProgress=!1;a.isInitialized=!0;c.saveToLocalStorage(a.news)},g=function(){a.loadInProgress=!0;c.getTitles(a.news.data.length).then(h)};
a.addedNew=function(){a.refresh();e.toggle("mcc.overlayEditorNews","off")};a.refresh=function(){a.newNews={published:!1,contents:"",ingress:"",title:""};c.reset();f();g()};a.atTheEnd=function(){a.loadInProgress||a.news.pagination.isLast||g()};c.init().then(h)}}}]);
angular.module("mcc").directive("mccNewsSelected",["$routeParams","$location","$http","$rootScope","mcc.newsData","mcc.toasterTranslate","dialogs",function(e,c,a,d,b,f,h){return{restrict:"E",scope:!0,templateUrl:"rest/mcc/templates/directives/newsSelected",link:function(g,n,p){g.id=e.id;g.news={title:"",contents:""};g.comments=[];var l=function(){g.comment={name:"",email:"",contents:""}};l();g.isInitialized=!1;b.getById(g.id).then(function(a){g.news=a.news;g.previous=a.news_previous;g.next=a.news_next;
g.isInitialized=!0});g.afterDelete=function(){d.toggle("mcc.overlayEditorNews","off");c.path("news")};g.loadComments=function(){a({method:"GET",url:"rest/news/comments/"+g.id}).success(function(a,b,c,f){g.comments=a.comments}).error(function(a,b,c,d){f.error(a.code)})};g.postReply=function(b){a({method:"PUT",data:g.comments[b],url:"rest/private/news/comment"}).success(function(a,b,c,d){f.success(a.dict);l();g.loadComments()}).error(function(a,b,c,d){f.error(a.dict)})};g.deleteComment=function(b){h.confirm(void 0,
void 0,{size:"sm"}).result.then(function(){a({method:"DELETE",url:"rest/private/news/comment/"+b}).success(function(a,b,c,d){f.success(a.dict);g.loadComments()}).error(function(a,b,c,d){f.error(a.dict)})})};g.postComment=function(){a({method:"POST",data:g.comment,url:"rest/news/comment/"+g.id}).success(function(a,b,c,d){f.success(a.dict);l();g.loadComments()}).error(function(a,b,c,d){f.error(a.dict)})};g.loadComments()}}}]);
angular.module("mcc").directive("mccOnChange",[function(){return{restrict:"A",scope:{fun:"=mccOnChange"},link:function(e,c,a){$(c).bind("change",function(){var a=$(c).data();void 0!=a?e.fun(a,$(c).val()):e.fun($(c).val())})}}}]);
angular.module("mcc").directive("mccOnClickPrompt",["$http","mcc.toasterTranslate",function(e,c){return{restrict:"A",scope:{value:"=mccOnClickPrompt",data:"=mccOnClickData"},link:function(a,d,b){var f=!1;d.bind("click",function(){f||(a.$watch("data",function(){e({method:b.mccOnClickMethod,url:b.mccOnClickUrl,data:a.data}).success(function(f,d,e,h){c.success(f.dict);a.data=f[b.mccOnClickObject]}).error(function(a,b,f,d){c.error(a.dict)})},!0),f=!0);var d=prompt(b.mccOnClickText,a.value);""!=d&&null!=
d&&void 0!=d&&(a.value=d,a.$apply())})}}}]);angular.module("mcc").directive("mccPagination",function(){return{restrict:"A",scope:"@",transclude:!0,template:"<div><ng-transclude></ng-transclude></div>",link:function(e,c,a){c.bind("scroll",function(){var d=window.innerHeight+c[0].scrollTop,b=c[0].children[0].offsetHeight-parseInt(a.heightMargin);if(d>b)e[a.mccPagination]()})}}});
angular.module("mcc").directive("mccPrintable",[function(){return{restrict:"A",link:function(e,c,a){c.bind("click",function(){for(var d=window.open(),b=document.styleSheets,f=[],e=0;e<b.length;e++){var g=b.item(e);null==g.href||"mccPrintableNoCss"in a&&null!=g.href.match(a.mccPrintableNoCss)||f.push(g.href)}b="";for(e=0;e<f.length;e++)b+='<link rel="stylesheet" href="'+f[e]+'" >';f=""==a.mccPrintable?$(c[0]).html():$("#"+a.mccPrintable).html();d.document.writeln("<html><head>"+b+"\n\n<style>input {display: none !important; }.no-print {display: none !important; }.only-print {display: block !important; }a {text-decoration: none !important; color: black !important;}</style></head><body>"+
f+"</body></html>")})}}}]);angular.module("mcc").directive("mccSideBarLeft",[function(){return{restrict:"A",scope:!0,templateUrl:"rest/mcc/templates/directives/sideBarLeft",link:function(e,c,a){e.sb=CONFIG.structure}}}]);
angular.module("mcc").directive("mccSideBarLeftLinks",["$rootScope","$location",function(e,c){return{restrict:"A",scope:{links:"=mccSideBarLeftLinks"},templateUrl:"rest/mcc/templates/directives/sideBarLeftLinks",link:function(a,d,b){a.click=function(b,d){"link"in b&&(2==arguments.length&&"path"in d?c.path(d.path+"/"+b.link):c.path(b.link));"overlay"in b&&e.toggle(b.overlay,"on");"url"in b&&window.open(b.url);a.hasChildLinks(b)||e.toggle("mainSidebar","off")};a.hasChildLinks=function(a){if("contents"in
a)for(var b=0;b<a.contents.length;b++)if("title"in a.contents[b]||"contents"in a.contents[b]&&hasChildLinks(a.contents[b]))return!0;return!1};a.show=function(a,b){return"title"in a?2==arguments.length&&null!=b?e.activeArea==b.path?!0:!1:"title"in a?"ishttps"in a&&a.ishttps?"isLoggedIn"in a?e.ishttps&&e.isLoggedIn===a.isLoggedIn:e.ishttps:"isLoggedIn"in a&&a.isLoggedIn?e.isLoggedIn==a.isLoggedIn:!0:!1:!1}}}}]);
angular.module("mcc").directive("mccTabToSpace",function(){return{restrict:"A",link:function(e,c,a){$(c).keydown(function(d){if(9==d.which){this.focus();for(var b=this.selectionStart,f="",e="",e=$(c).val(),f=e.substr(0,b),e=e.substr(b,e.length),g=0;g<a.tabToSpace;g++)f+=" ";$(c).val(f+e);$(c).selectRange(parseInt(b)+parseInt(a.tabToSpace));d.preventDefault()}})}}});
angular.module("mcc").directive("mccTooltip",function(){return{restrict:"A",link:function(e,c,a){var d=document.createElement("div");$(c[0]).css({position:"relative"});$(d).hide();$(d).css({position:"absolute","z-index":1E4}).html(a.mccTooltip).addClass("mcc-tooltip").appendTo(c);c.bind("mousemove",function(a){$(d).width();var c=$(d).width();$(d).css({top:a.offsetY-c/2+8,left:a.offsetX+10})});c.bind("mouseenter",function(){$(d).fadeIn(100)});c.bind("mouseleave",function(){$(d).fadeOut(100)})}}});
angular.module("mcc").service("mcc.analytics",[function(){return{send:function(e,c){ga("send",e,c)}}}]);angular.module("mcc").service("mcc.code",["mcc.$http","mcc.crud",function(e,c){return new c("rest/private/","rest/private/","data")}]);
angular.module("mcc").service("mcc.crud",["mcc.$http",function(e){return function(c,a,d,b){var f=4===arguments.length;this.create=f?function(a){return e.postViaDefer(c+b+"/"+a[b+"_id"]+"/"+d,a)}:function(a){return e.postViaDefer(c+d,a)};this.get=function(a){return e.getViaDefer(c+d+"/"+a)};this.getPub=function(b){return e.getViaDefer(a+d+"/"+b)};var h;f?(f=function(a){return e.getViaDefer(c+b+"/"+a+"/"+d+"_all")},h=function(c){return e.getViaDefer(a+b+"/"+c+"/"+d+"_all")}):(f=function(){return e.getViaDefer(c+
d+"_all")},h=function(){return e.getViaDefer(c+d+"_all")});this.getAll=f;this.getAllPub=h;this.update=function(a){return e.putViaDefer(c+d+"/"+a.id,a)};this.remove=function(a){return e.deleteViaDefer(c+d+"/"+a)}}}]);
angular.module("mcc").service("mcc.$http",["$http","$q",function(e,c){var a=function(a,b,f){var h=c.defer();2>arguments.length&&(b="get");var g={method:b,url:a};2<arguments.length&&null!==f&&(g.data=f);e(g).success(function(a,b,c,d){h.resolve({data:a,status:b,headers:c,config:d})}).error(function(a,b,c,d){console.log("Could not get data");h.resolve({data:a,status:b,headers:c,config:d})});return h.promise};return{customViaDefer:a,getViaDefer:function(c){return a(c)},deleteViaDefer:function(c){return a(c,
"delete")},postViaDefer:function(c,b){return a(c,"post",b)},putViaDefer:function(c,b){return a(c,"put",b)}}}]);
angular.module("mcc").service("mcc.newsData",function(e,c,a){var d=function(a){return function(){return e({method:"get",url:a}).then(f,h)}},b=function(b){b=1===arguments.length?b:0;0==b&&d("rest/news/latest/timestamp")().then(function(b){a.newsTimestamp=b.timestamp});return d("rest/news/titles/"+b)()},f=function(a){return a.data},h=function(a){return angular.isObject(a.data)&&a.data.message?c.reject(a.data.message):c.reject("An unknown error occurred.")};return{getTitles:b,getById:function(a){return d("rest/news/"+
a)()},init:function(){var e=a.news,f=a.newsTimestamp,h=(new Date).getTime();if(null==e||null==e.news||0==e.news.length||6E5<h-e.updated)return b(0);var h=d("rest/news/latest/timestamp"),l=c.defer();h().then(function(a){f==a.timestamp?l.resolve(e):b().then(function(a){l.resolve(a)})});return l.promise},saveToLocalStorage:function(b){b.updated=(new Date).getTime();a.news=b},reset:function(){delete a.news}}});
angular.module("mcc").service("mcc.restClient",["mcc.toasterTranslate","dialogs",function(e,c){return{init:function(a){this.addInit=function(c){a.selected[a.object]=c;"cb"in a&&"addInit"in a.cb&&a.cb.addInit(c)};this.editInit=function(c){a.selected[a.object]=c;"cb"in a&&"editInit"in a.cb&&a.cb.editInit(c)};this.remove=function(d){c.confirm(void 0,void 0,{size:"sm"}).result.then(function(){a.service.remove(d).then(function(b){e.report(b.status,b.data.dict);"cb"in a&&"remove"in a.cb&&a.cb.remove(b)})})};
this.save=function(){"cb"in a&&"savemw"in a.cb&&a.cb.savemw();var c=function(b){a.object in b.data&&(a.selected[a.object]=b.data[a.object]);e.report(b.status,b.data.dict);"cb"in a&&"save"in a.cb&&a.cb.save(b.data)};"id"in a.selected[a.object]?a.service.update(a.selected[a.object]).then(c):a.service.create(a.selected[a.object]).then(c)}}}}]);
angular.module("mcc").service("mcc.toasterTranslate",["toaster","$translate",function(e,c){var a=function(a){b("error",a)},d=function(a){b("success",a)},b=function(a,b){var d="TOASTER."+a.toUpperCase();c([d,b]).then(function(c){e.pop(a,c[d]+"!",c[b])})};return{error:a,info:function(a){b("info",a)},success:d,common:function(a,c){b(a,c)},report:function(b,c){200===b?d(c):a(c)}}}]);
angular.module("mcc").service("mcc.user",["$localStorage","$rootScope","$http","mcc.toasterTranslate",function(e,c,a,d){return{autoLogin:function(){c.ishttps&&a({method:"GET",url:"rest/private/auth"}).success(function(a,e,d,g){c.isLoggedIn=!0;c.user=a.user}).error(function(a,e,d,g){c.isLoggedIn=!1;c.user={}})},login:function(b,c){return a({method:"POST",data:{username:b,password:c},url:"rest/private/auth"})},logout:function(){delete e.user;delete e.isLoggedIn;return a({method:"GET",url:"rest/private/auth/logout"})},
setLoginData:function(a,e){c.isLoggedIn=a;c.user=2==arguments.length&&a?e.user:{}},setToScope:function(a){c.isLoggedIn?(a.user=c.user,a.isLoggedIn=!0):a.isLoggedIn=!1}}}]);
(function(e,c,a){e.figureEditor=function(a){var b={image:null,param:null,scale:1,cropPoints:[],loaderCb:function(){}};b.param=a;var c=function(){return"canvas"in b.param?b.param.canvas:document.getElementById(b.param.id)},e=function(){b.img.removeEventListener("load",e);console.log("loaded");b.loaderCb();g()},g=function(){var a=c(),e=c().getContext("2d"),d=b.img.width,g=b.img.height,h=Math.min(d>b.param.maxWidth?b.param.maxWidth/d:1,g>b.param.maxHeight?b.param.maxHeight/g:1);b.scale=h;d=Math.round(d*
h);g=Math.round(g*h);a.width=d;a.height=g;e.drawImage(b.img,0,0,d,g)};this.drawFullImage=function(a,c){var d=new FileReader;b.img=new Image;b.loaderCb=c;b.img.addEventListener("load",e,!1);d.onload=function(a){b.img.src=a.target.result};d.readAsDataURL(a)};this.setCropPoint=function(a,e){if(2>b.cropPoints.length)b.cropPoints.push({x:a,y:e});else{var d=Math.sqrt(Math.pow(b.cropPoints[0].x-a,2)+Math.pow(b.cropPoints[0].y-e,2)),h=Math.sqrt(Math.pow(b.cropPoints[1].x-a,2)+Math.pow(b.cropPoints[1].y-e,
2));b.cropPoints[d<h?0:1]={x:a,y:e}}g();for(var d=c().getContext("2d"),h=c(),k=0;k<b.cropPoints.length;k++)d.beginPath(),d.moveTo(b.cropPoints[k].x,0),d.lineTo(b.cropPoints[k].x,h.height),d.stroke(),d.beginPath(),d.moveTo(0,b.cropPoints[k].y),d.lineTo(h.width,b.cropPoints[k].y),d.stroke()};this.getCropPoints=function(){for(var a=[],c=0;c<b.cropPoints.length;c++)a.push({x:Math.round(b.cropPoints[c].x/b.scale),y:Math.round(b.cropPoints[c].y/b.scale)});return a};this.setProjectPoint=function(a,b){}}})(window.mcc=
window.mcc||{},jQuery);
